# Generated by Django 3.0.6 on 2020-07-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20200717_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='abc', max_length=200),
        ),
    ]
